### ISSUE TITLE
Mirrored version for Lefties

### ISSUE THREAD

**Issue by chatelao** [TweetyDaBird/DaNumPad#1]
Situation:
- My wife is a lefty/southpaw and I would like to make her a NumPad.

Wish:
- She would like a 100% mirrored version of the usual layout.

Idea:
- Is it possible to modify the NumPad to be similar to the Lotus58 a 100% flippable?
- This would allow me to make 5 NumPads, Lefty or Righty, from one PCB order.

**Comment by TweetyDaBird** [comment]
> Situation:
> 
> - My wife is a lefty/southpaw and I would like to make her a NumPad.
> 
> 
> 
> Wish:
> 
> - She would like a 100% mirrored version of the usual layout.
> 
> 
> 
> Idea:
> 
> - Is it possible to modify the NumPad to be similar to the Lotus58 a 100% flippable?
> 
> - This would allow me to make 5 NumPads, Lefty or Righty, from one PCB order.

Unfortunately that won't really work as the pins for the controller would need to flip as well, and the signals there are already crammed in as tight as can be, with a fair few compromises for the signals removed. 

But, I'd be happy to flip the design over and make a lefty one for you, as I'm fairly certain I can make the signals fit either way, although I very much doubt they can be reversible. 

Watch here the following days/weeks.

**Comment by TweetyDaBird** [comment]
Well, it sort of turned into another numpad with other properties. [UnOrthoDox](https://github.com/TweetyDaBird/UnOrthoDox)

But it is a numpad, and it is reversible.
